### ISSUE TITLE
Look up g:plug_home in order to run external scripts

### ISSUE THREAD

**Issue by mvrozanti** [Kody-Quintana/bspwm_border_color#1]
With `:echo g:plug_home`

I use nvim and I don't vundle so those hardcoded paths are double-wrong for me lol

**Comment by Kody-Quintana** [comment]
1727b60 should fix this, let me know if it doesn't (I also use nvim but I just point everything to my old vim folders)

**Comment by mvrozanti** [comment]
It does! Thanks man cool plugin

**Comment by mvrozanti** [comment]
Actually I just realized it worked for me because I started pointing to the old folder as well but there's also

https://github.com/Kody-Quintana/bspwm_border_color/blob/1727b60dcb1c164d42d1ec67d7ac0a8254c1d922/listener_launcher#L6

and 
https://github.com/Kody-Quintana/bspwm_border_color/blob/1727b60dcb1c164d42d1ec67d7ac0a8254c1d922/bspwm_border_listener#L10

**Comment by mvrozanti** [comment]
Also, I'm not sure if it's because I use tmux or something, but I can't get the unfocusing behavior in the README when I switch windows where the border turns white: https://i.imgur.com/41xTP88.gif , even though I installed amerlyq/vim-focus-autocmd

**Comment by Kody-Quintana** [comment]
that looks like the bspwm_border_listener script is either not running or not working, the way it works is kind of hacky it just reads the xtitle every time the focus changes and if it isn't vim it sets the color back to the default focus color. Its probably not running because of that hard coded path that I forgot to fix. Let me fix those two paths and see if that issue still persists after that

**Comment by Kody-Quintana** [comment]
ok try out 09b68fb and let me know if that works
edit: actually try out 7ea3ce8 I had the path to bash hard coded and broke something, this should fix that

**Comment by mvrozanti** [comment]
Still getting the same behavior. I suspect it's got something to do with me using tmux. `xtitle` never seems to output ᴠɪᴍ

**Comment by Kody-Quintana** [comment]
Can you confirm that the listener script is actually running? What is the xtitle of the window when nvim is open?

**Comment by mvrozanti** [comment]
Oh my bad it actually is working! I think I had the old listener running. 

One more thing though: it _sometimes_ doesn't seem to turn green when focus is regained, I need to type something for it to turn green again, like so: https://i.imgur.com/iwYVaUf.gif

It's really minor, but I'm not sure if this is expected behavior

**Comment by Kody-Quintana** [comment]
that behavior is supposed to be handled by the line
```
autocmd FocusGained * :silent execute "!" . s:plugin_path . "set " . shellescape(mode())
```
some terminal emulators don't support this functionality, which terminal are you using?

**Comment by mvrozanti** [comment]
kitty

**Comment by Kody-Quintana** [comment]
I'm also using kitty so that's not the problem. Can you confirm that the FocusGained autocmd works? Try adding something like
```
autocmd FocusGained * :echomsg "test123"
```
to your configuration

**Comment by mvrozanti** [comment]
https://i.imgur.com/vgrNFBh.gif

It's a bit hard to see but at the end of the gif FocusGained seems to trigger but the recoloring doesn't

**Comment by mvrozanti** [comment]
Adding a 0.03 seconds sleep to FocusGained argument makes it work lol https://i.imgur.com/tqRPa4A.gif , still don't know why though

**Comment by Kody-Quintana** [comment]
Ok this is a tmux issue like you originally suspected.
I was able to get things working by adding
```
set-option -g set-titles on
set -g focus-events on
set-option -g set-titles-string "#T"
```
to `~/.tmux.conf`
one issue that remains is changing focus between a tmux pane running vim to one that isn't won't correctly set the border color back to the default.

**Comment by mvrozanti** [comment]
That didn't work for me for some reason

**Comment by Kody-Quintana** [comment]
Do you have anything else in your tmux config? What does the xtitle get set to what you focus tmux running vim?

**Comment by mvrozanti** [comment]
I think I found the problem, I already spawn a kitty instance with a specific title `_zsh_` (on the top right in the gif) so it doesn't work on that terminal but it works on a non-titled one (bottom right): https://i.imgur.com/ozH4yjf.gif

**Comment by Kody-Quintana** [comment]
Glad you got it working. Checking the xtitle isn't a great solution because so many things can change it before the listener script will see it but it was the easiest way I could think of. If there's nothing else I think this issue can be closed

**Comment by mvrozanti** [comment]
Thanks again for the help and the plugin!

**Comment by Kody-Quintana** [comment]
No problem, thanks for trying it out
